image dark_deformed_hallway = Movie(play='images/backgrounds/bg_dark_deformed_hallway.webm')
image deformed_hallway_1 = Movie(play='images/backgrounds/bg_deformed_hallway_1.webm')
image deformed_hallway_2 = Movie(play='images/backgrounds/bg_deformed_hallway_2.webm')
image street = Movie(play='images/backgrounds/bg_street.webm')
image university = Movie(play='images/backgrounds/bg_university.webm')
image basement = Movie(play='images/backgrounds/bg_basement.webm')
image aud_distorted = Movie(play='images/backgrounds/bg_aud_distorted.webm')
image archway_day = 'images/backgrounds/bg_archway_day.png'
image archway_evening = 'images/backgrounds/bg_archway_evening.png'
image archway_night = 'images/backgrounds/bg_archway_night.png'
image street_static = 'images/backgrounds/bg_street.png'
image world_between_worlds = 'images/backgrounds/bg_world_between_worlds.png'
image hallway = 'images/backgrounds/bg_hallway.png'
image aud_14_empty = 'images/backgrounds/bg_aud14_nothing.png'
image aud_14_docs = 'images/backgrounds/bg_aud_14_docs.png'
image aud_14_magistrants = 'images/backgrounds/bg_aud14_magistrants.png'
image aud_149 = 'images/backgrounds/bg_aud_149.png'
image bismarcks_aud = 'images/backgrounds/bg_bismarcks_aud.png'
image iszf = 'images/backgrounds/bg_iszf.png'
image hall_iszf = 'images/backgrounds/bg_hall_iszf.png'
image staff_room = 'images/backgrounds/bg_staff_room.png'
image staff_room_2 = 'images/backgrounds/bg_staff_room_2.png'
image flat = 'images/backgrounds/bg_flat.png'
